# Generated by Django 5.0.7 on 2024-07-25 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('item_selector', models.CharField(max_length=200)),
                ('title_selector', models.CharField(max_length=200)),
                ('price_selector', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=500)),
                ('price', models.CharField(max_length=200)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ScrapeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('item_selector', models.CharField(max_length=200)),
                ('title_selector', models.CharField(max_length=200)),
                ('price_selector', models.CharField(max_length=200)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
